// default package
// Generated 22 nov 2023 13:01:39 by Hibernate Tools 5.2.13.Final

package Model;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Musician generated by hbm2java
 */
@Entity
@Table(name = "Musician", catalog = "OrchestraDB")
public class Musician implements java.io.Serializable {

	private Integer musicianId;
	private Orchestra orchestra;
	private String musicianName;
	private String instrument;
	private Set<Orchestra> orchestras = new HashSet<Orchestra>(0);

	public Musician() {
	}

	public Musician(Orchestra orchestra, String musicianName, String instrument, Set<Orchestra> orchestras) {
		this.orchestra = orchestra;
		this.musicianName = musicianName;
		this.instrument = instrument;
		this.orchestras = orchestras;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "MusicianID", unique = true, nullable = false)
	public Integer getMusicianId() {
		return this.musicianId;
	}

	public void setMusicianId(Integer musicianId) {
		this.musicianId = musicianId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idOrchestra")
	public Orchestra getOrchestra() {
		return this.orchestra;
	}

	public void setOrchestra(Orchestra orchestra) {
		this.orchestra = orchestra;
	}

	@Column(name = "MusicianName")
	public String getMusicianName() {
		return this.musicianName;
	}

	public void setMusicianName(String musicianName) {
		this.musicianName = musicianName;
	}

	@Column(name = "Instrument", length = 50)
	public String getInstrument() {
		return this.instrument;
	}

	public void setInstrument(String instrument) {
		this.instrument = instrument;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "musicians_1")
	public Set<Orchestra> getOrchestras() {
		return this.orchestras;
	}

	public void setOrchestras(Set<Orchestra> orchestras) {
		this.orchestras = orchestras;
	}

}
